### ISSUE TITLE
When a row is modified, ALL columns are entered into the log

### ISSUE THREAD

**Issue by ChristineBoersen** [johannbrink/EFAuditing#1]
When a row is modified, ALL columns are entered into the log as modified, irrespective of if the column contents are changed.

I tried a simple workaround (via downloading your source to see if it would work) in GetAuditLogs to compare the CurrentValue and OriginalValue when the entitystate is Modified, but both CurrentValue and OriginalValue both seem to have the same value (CurrentValue) from the underlying plumbing. 

Shouldn't the underlying framework be supplying OriginalValue as the value _BEFORE_ the save?

**Comment by ChristineBoersen** [comment]
OK.. It seems in SaveChanges, you call (line 203) var result = base.SaveChanges() _BEFORE_ you call GetAuditLogs (line 205). This causes the CurrentValue and OriginalValue to end up being the same during the auditing routine.

**Comment by johannbrink** [comment]
Thanks for the issue log. Will need to investigate. I have to Call base.SaveChanges before building the auditLogs because building the audit logs prior to this causes all the key fields to have -1, -2 etc values

**Comment by ChristineBoersen** [comment]
I noticed that behavior as well when I started testing my work-around (which didn't surprise me as it acted like a disconnected recordset behavior, pre-save), I'm trying a couple of things real quick to see if a workaround is "easy"

**Comment by ChristineBoersen** [comment]
I think you are going to find out you have to re-read the record _THEN_ save the audit log, for "added" records so you have the ID, otherwise, you won't be able to capture "changes" effectively (ie, you will show the behavior I saw above with originalvalue and currentvalue always matching). And yes, I know, a bit of work to accomplish. You may have to grab the code out of the base class's SaveChanges and hook the auditing in deeper (which just sounds dirty).

**Comment by johannbrink** [comment]
Yeah I noticed the values of original and current are the same, the result of the change to get the ID values of added entities. I will have a look sometime today to see if I can sort it out.

**Comment by ChristineBoersen** [comment]
Also, I recommend adding the following (indented green) lines to AuditLogBuilder.cs so that once you fix the saving issue, then only modified columns are logged.

![image](https://cloud.githubusercontent.com/assets/13676509/10134756/2c83e29c-65b6-11e5-9345-2123b6fd2e3b.png)

**Comment by johannbrink** [comment]
Hi, I update the code to build logs for modified and deleted prior to base.SaveChanges and to build logs for Added after calling base.SaveChanges. New code committed and publishing the new NuGet package now.
