### ISSUE TITLE
Grab changes from Fork

### ISSUE THREAD

**Issue by ChristineBoersen** [johannbrink/EFAuditing#2]
Johann,
Please check the changes I have in my fork  ChristineBoersen/EFAuditing.  You can review them this way without me messing up your branch. Let me know what you think!

Changes I've added
A) Set a variable to "now" earlier in the auditing, then reuse it for all the audit records in that "batch"
B) Add an GUID AuditBatchID to the AuditLog entity
C) Set the AuditBatchID using system.runtime.interopservices to call the UuidCreateSequential function that Sql Server uses natively so that all audits from a batch are linked to a uniqueID
D) Added index to the AuditBatchID created in step B.

Thanks in advance.

**Comment by johannbrink** [comment]
Hi, interesting changes. I think I'm not going to pull those changes into my branch as they seem quite specific to your implementation. I like what you are doing though and appreciate you using my humble code as a starting point.

**Comment by ChristineBoersen** [comment]
Not a problem, hence why I forked it in case you didn’t feel it was appropriate. I wanted to make sure that I can track changes as a batch, hence adding that functionality. 

In previous logging implementations I have written, it was a requirement since when a system gets really busy, it can be difficult to determine how changes happened if the entire batch isn’t looked at, as a single “transaction”. Use Case (that actually happened) We once had to use a previous log to recreate a months’ worth of data due to a bad delete and a DBA who didn’t have backups set properly, so having the batch information was crucial in the reconstruction of the data.

**Comment by johannbrink** [comment]
Cool, will look at adding it. Is it really necessary for the sequencial Guid? Does it actually connect to SQL to get the Guid? If so, does it just use the connection string from the EF DBContext? I'm just a bit wary of the external call as I don't understand that completely.

**Comment by ChristineBoersen** [comment]
It’s using the same functionality that SQL Server uses to generate a sequential id, but it is _NOT_ calling sql server for the information. It is using the same low level call that sql server uses, but since it is run wherever the application is running, it would NOT be sequential with a call made on the sql server (unless POSSIBLY they are on the same machine).  In theory, UUIDSequentialID is unique to the machine, but not guaranteed to be sequential across machine reboots. I felt this was better than a query to get the MaxID from the database (which I suspect was the same concern you were having as well).
